# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-nBWi9hs9P0HFwbVepXYwwX7JMw-CCz
"""

import pandas as pd
import numpy as np

data = []

for age in range(1,100):
 if age  <=20:
  sport = "Cricket"
 elif age <= 40:
    sport = "Football"
 elif age <= 60:
      sport = "Hockey"
 elif age <= 80:
      sport = "Dogball"
 else:
        sport = "Vollyball"
 data.append([age,sport])

data.append([age,sport])

df=pd.DataFrame(data, columns=["Age","Sport"])

print(df)

df.to_csv("sports_dataset.csv")

"""step 2: Data Augmentation"""

df = pd. read_csv("sports_dataset.csv")

df.info()

df.isnull().sum()

df.describe()

df.head(10)

len(df)

#remove duplicate values
df = df.drop_duplicates()

#remove rows  with missing values
df = df.dropna()

#remove invallid ages
df = df[(df["Age"]>=1) & (df["Age"] <=100)]

display(df)

df.shape

df.to_csv("sports_dataset_cleaned.csv",index=False)

df = pd.read_csv("sports_dataset_cleaned.csv")

df.shape

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#load dataset
df = pd.read_csv("sports_dataset_cleaned.csv")

# feature and target
x = df[["Age"]]
y = df[["Sport"]]

# split data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42 )

# Train Decision Trees
model = DecisionTreeClassifier(random_state=42)
model.fit(x_train,y_train)

#  prediction
y_pred = model.predict(x_test)

# accuracy
accuracy = accuracy_score(y_test,y_test)
print("Accuracty Score",accuracy)
Accuracty : 0.95

Age = 35
prediction = model.predict([[age]])
print(prediction)

test_ages = [[15],[28],[102],[-1]]
pridction = model.predict(test_ages)
print(prediction)

"""Visualize Model"""

import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.scatter(df["Age"],df["Sport"])
plt.xlabel("Age")
plt.ylabel("Sport")
plt.title("Age vs Sport")
plt.show()

import pickle
# save model
with open("sports_model.pkl","wb") as file:
  pickle.dump(model,file)

  print("model saved succesfully as sports_model.pk1")